### ISSUE TITLE
Build process exit with code 1 after ESPHome Update to 2023.8.1

### ISSUE THREAD

**Issue by TheRealFalseReality** [esphome/esphome-project-template#10]
Logs: https://github.com/TheRealFalseReality/aquapi/actions/runs/5971333448/job/16200240502

Using your template for my project: https://github.com/TheRealFalseReality/aquapi

But it seems like then ESPHome updated to 2023.8.1, but now getting this error:

```
    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
      raise ScannerError(None, None,
  yaml.scanner.ScannerError: mapping values are not allowed here
    in "<unicode string>", line 437, column 24:
        ssid: \033[5m    name: Connected SSID\033[6m
                             ^
  
  Error: Process completed with exit code 1.
```

This started to fail only after ESPHome updated to 8.1, all I did was edit my README.md file to trigger the Action. But since, it hasn't been able to build and publish....

Any ideas?

**Comment by TheRealFalseReality** [comment]
It built after removing the following lines from the Wifi sensor:
```
  # Wifi Info
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
```

Tried twice with adding the above lines but GitHub actions will not build with them included. I just removed them to get it to build, as a workaround. Not a critical issue, however.

**Comment by jesserockz** [comment]
There was a bug in that ESPHome version with the wifi_info ssid sub-sensor that has since been fixed.
