### ISSUE TITLE
Error Invalid workflow file : .github/workflows/publish.yml#L10

### ISSUE THREAD

**Issue by jowgn** [esphome/esphome-project-template#3]
Following the Readme I set up a fork to https://github.com/Arvernus/Shelly-for-ESPHome but if I try to build it I get the following error:
`The workflow is not valid. In .github/workflows/publish.yml (Line: 10, Col: 11): Error from called workflow esphome/workflows/.github/workflows/publish.yml@main (Line: 72, Col: 9): Unexpected value 'secrets'`

**Comment by jowgn** [comment]
@jesserockz am I doing something wrong here?

**Comment by jesserockz** [comment]
Hi @jowgn.

I just merged your PR into workflows, and also made a few more updates on both the workflows and this template to fully rmeove all references to the manual secrets which should fix the problem.
