### ISSUE TITLE
The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by JamesSwift** [esphome/esphome-project-template#9]
Hi,

I'm using your template for my esphome project: https://github.com/JamesSwift/localbytes-plug-pm

But I'm getting errors on the "publish" step:
```
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
```
https://github.com/JamesSwift/localbytes-plug-pm/runs/6430826564?check_suite_focus=true

Any idea's what's going wrong here?

**Comment by jesserockz** [comment]
I will take a look when I can. Looks like a bug in the gh-pages action perhaps. I see there are new versions of it so maybe just bumping it will help. I will reply back once that is done.

**Comment by JamesSwift** [comment]
Hi @jesserockz, just wondering if you managed to find a solution to this?

**Comment by maikischa** [comment]
I just tried it and get the same error

**Comment by TNTLarsn** [comment]
Please ignore the mentions above. **PR13 is not related!**

**Comment by lucas2lab** [comment]
Hello, I have the same error the process "[build / Publish new firmware and website to GitHub Pages]" Fail
